name: LM_Items
version: ${project.version}
main: io.github.stumper66.lm_items.LM_Items
softdepend:
  - MythicMobs
  - HeadDatabase
  - UltimaAddons
api-version: '1.13'
load: POSTWORLD
author: stumper66
description: ${project.description}
website: 'https://github.com/lokka30/LevelledMobs/wiki'

commands:
  lm_items:
    description: Manage LM Items
    aliases: [ lmi ]

permissions:
  lm_items.*:
    description: 'Access to all LM Items.'
    default: op
