name: LM_Items
version: ${project.version}
main: me.stumper66.lm_items.LM_Items
softdepend:  [ ExecutableItems, MMOItems ]
api-version: '1.16'
load: POSTWORLD
author: stumper66
description: ${project.description}
website: 'https://github.com/lokka30/LevelledMobs/wiki'

commands:
  lm_items:
    description: Manage LM Items
    aliases: [ lmi ]
    usage:

permissions:
  lm_items.*:
    description: 'Access to all LM Items.'
    default: op